### ISSUE TITLE
 beamer_presentation用metropolis主题， 代码部分能否加背景？

### ISSUE THREAD

**Issue by perlatex** [XiangyunHuang/R-Markdown-Template#1]
用metropolis主题，
```
output: 
  beamer_presentation: 
    citation_package: natbib
    theme: metropolis
    fonttheme: structurebold
    colortheme: seahorse
    fig_caption: yes
    incremental: no
    keep_tex: no
    latex_engine: xelatex
    slide_level: 2
    toc: no
```

希望， Rmarkdown中的代码能有背景色
```{r}
# Embedding code
x = 2
y = 3

x + y
```
请问能怎么调？
